name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          bazel build //:for_all_platforms
          mv bazel-out/darwin_arm64-opt/bin/external/libarchive\~/tar/bsdtar tar_darwin_arm64
          mv bazel-out/darwin_amd64-opt/bin/external/libarchive\~/tar/bsdtar tar_darwin_amd64
          mv bazel-out/linux_arm64_musl-opt/bin/external/libarchive\~/tar/bsdtar tar_linux_arm64
          mv bazel-bin/external/libarchive\~/tar/bsdtar  tar_linux_amd64
          shasum -a 256 tar* > SHA256.txt
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            ./tar*
            SHA256.txt
